/* tslint:disable */
/* eslint-disable */
/**
 * Crypto Map API documentation
 * The Establishments map API is serves a list of establishments that accept crypto as a payment method.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AutocompleteApiCurrenciesInner
 */
export interface AutocompleteApiCurrenciesInner {
    /**
     * 
     * @type {string}
     * @memberof AutocompleteApiCurrenciesInner
     */
    symbol: string;
    /**
     * 
     * @type {string}
     * @memberof AutocompleteApiCurrenciesInner
     */
    name: string;
}

/**
 * Check if a given object implements the AutocompleteApiCurrenciesInner interface.
 */
export function instanceOfAutocompleteApiCurrenciesInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "symbol" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function AutocompleteApiCurrenciesInnerFromJSON(json: any): AutocompleteApiCurrenciesInner {
    return AutocompleteApiCurrenciesInnerFromJSONTyped(json, false);
}

export function AutocompleteApiCurrenciesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AutocompleteApiCurrenciesInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'symbol': json['symbol'],
        'name': json['name'],
    };
}

export function AutocompleteApiCurrenciesInnerToJSON(value?: AutocompleteApiCurrenciesInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'symbol': value.symbol,
        'name': value.name,
    };
}

