/* tslint:disable */
/* eslint-disable */
/**
 * Crypto Map API documentation
 * The Shop Directory API is serves a list of shops that accept crypto as a payment method.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CurrencyInner
 */
export interface CurrencyInner {
    /**
     * 
     * @type {string}
     * @memberof CurrencyInner
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CurrencyInner
     */
    symbol: string;
}

/**
 * Check if a given object implements the CurrencyInner interface.
 */
export function instanceOfCurrencyInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "symbol" in value;

    return isInstance;
}

export function CurrencyInnerFromJSON(json: any): CurrencyInner {
    return CurrencyInnerFromJSONTyped(json, false);
}

export function CurrencyInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrencyInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'symbol': json['symbol'],
    };
}

export function CurrencyInnerToJSON(value?: CurrencyInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'symbol': value.symbol,
    };
}

