/* tslint:disable */
/* eslint-disable */
/**
 * Crypto Map API documentation
 * The Establishments map API is serves a list of establishments that accept crypto as a payment method.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EstablishmentCandidateResponse
 */
export interface EstablishmentCandidateResponse {
    /**
     * 
     * @type {string}
     * @memberof EstablishmentCandidateResponse
     */
    message: string;
}

/**
 * Check if a given object implements the EstablishmentCandidateResponse interface.
 */
export function instanceOfEstablishmentCandidateResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function EstablishmentCandidateResponseFromJSON(json: any): EstablishmentCandidateResponse {
    return EstablishmentCandidateResponseFromJSONTyped(json, false);
}

export function EstablishmentCandidateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EstablishmentCandidateResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function EstablishmentCandidateResponseToJSON(value?: EstablishmentCandidateResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
    };
}

