/* tslint:disable */
/* eslint-disable */
/**
 * Crypto Map API documentation
 * The Shop Directory API is serves a list of shops that accept crypto as a payment method.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GeoLocation
 */
export interface GeoLocation {
    /**
     * 
     * @type {string}
     * @memberof GeoLocation
     */
    type?: GeoLocationTypeEnum;
    /**
     * 
     * @type {Array<number>}
     * @memberof GeoLocation
     */
    coordinates: Array<number>;
}


/**
 * @export
 */
export const GeoLocationTypeEnum = {
    Point: 'Point'
} as const;
export type GeoLocationTypeEnum = typeof GeoLocationTypeEnum[keyof typeof GeoLocationTypeEnum];


/**
 * Check if a given object implements the GeoLocation interface.
 */
export function instanceOfGeoLocation(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "coordinates" in value;

    return isInstance;
}

export function GeoLocationFromJSON(json: any): GeoLocation {
    return GeoLocationFromJSONTyped(json, false);
}

export function GeoLocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeoLocation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : json['type'],
        'coordinates': json['coordinates'],
    };
}

export function GeoLocationToJSON(value?: GeoLocation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'coordinates': value.coordinates,
    };
}

