/* tslint:disable */
/* eslint-disable */
/**
 * Crypto Map API documentation
 * The Shop Directory API is serves a list of shops that accept crypto as a payment method.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LocationCandidateBody
 */
export interface LocationCandidateBody {
    /**
     * 
     * @type {string}
     * @memberof LocationCandidateBody
     */
    google_place_id: string;
    /**
     * 
     * @type {string}
     * @memberof LocationCandidateBody
     */
    token: string;
    /**
     * 
     * @type {string}
     * @memberof LocationCandidateBody
     */
    name: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof LocationCandidateBody
     */
    currencies: Array<string>;
}

/**
 * Check if a given object implements the LocationCandidateBody interface.
 */
export function instanceOfLocationCandidateBody(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "google_place_id" in value;
    isInstance = isInstance && "token" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "currencies" in value;

    return isInstance;
}

export function LocationCandidateBodyFromJSON(json: any): LocationCandidateBody {
    return LocationCandidateBodyFromJSONTyped(json, false);
}

export function LocationCandidateBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocationCandidateBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'google_place_id': json['google_place_id'],
        'token': json['token'],
        'name': json['name'],
        'currencies': json['currencies'],
    };
}

export function LocationCandidateBodyToJSON(value?: LocationCandidateBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'google_place_id': value.google_place_id,
        'token': value.token,
        'name': value.name,
        'currencies': value.currencies,
    };
}

