/* tslint:disable */
/* eslint-disable */
/**
 * Crypto Map API documentation
 * The Shop Directory API is serves a list of shops that accept crypto as a payment method.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LocationIssueBody
 */
export interface LocationIssueBody {
    /**
     * 
     * @type {string}
     * @memberof LocationIssueBody
     */
    issue_category_id: string;
    /**
     * 
     * @type {string}
     * @memberof LocationIssueBody
     */
    google_place_id: string;
    /**
     * 
     * @type {string}
     * @memberof LocationIssueBody
     */
    token: string;
    /**
     * 
     * @type {string}
     * @memberof LocationIssueBody
     */
    description: string;
}

/**
 * Check if a given object implements the LocationIssueBody interface.
 */
export function instanceOfLocationIssueBody(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "issue_category_id" in value;
    isInstance = isInstance && "google_place_id" in value;
    isInstance = isInstance && "token" in value;
    isInstance = isInstance && "description" in value;

    return isInstance;
}

export function LocationIssueBodyFromJSON(json: any): LocationIssueBody {
    return LocationIssueBodyFromJSONTyped(json, false);
}

export function LocationIssueBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocationIssueBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'issue_category_id': json['issue_category_id'],
        'google_place_id': json['google_place_id'],
        'token': json['token'],
        'description': json['description'],
    };
}

export function LocationIssueBodyToJSON(value?: LocationIssueBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'issue_category_id': value.issue_category_id,
        'google_place_id': value.google_place_id,
        'token': value.token,
        'description': value.description,
    };
}

