/* tslint:disable */
/* eslint-disable */
/**
 * Crypto Map API documentation
 * The Shop Directory API is serves a list of shops that accept crypto as a payment method.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LocationIssue
 */
export interface LocationIssue {
    /**
     * 
     * @type {string}
     * @memberof LocationIssue
     */
    label: string;
    /**
     * 
     * @type {number}
     * @memberof LocationIssue
     */
    id: number;
}

/**
 * Check if a given object implements the LocationIssue interface.
 */
export function instanceOfLocationIssue(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "label" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function LocationIssueFromJSON(json: any): LocationIssue {
    return LocationIssueFromJSONTyped(json, false);
}

export function LocationIssueFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocationIssue {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'label': json['label'],
        'id': json['id'],
    };
}

export function LocationIssueToJSON(value?: LocationIssue | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'label': value.label,
        'id': value.id,
    };
}

