/* tslint:disable */
/* eslint-disable */
/**
 * Crypto Map API documentation
 * The Shop Directory API is serves a list of shops that accept crypto as a payment method.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PickupPlaceInformationPlusCode
 */
export interface PickupPlaceInformationPlusCode {
    /**
     * 
     * @type {string}
     * @memberof PickupPlaceInformationPlusCode
     */
    compound_code: string;
    /**
     * 
     * @type {string}
     * @memberof PickupPlaceInformationPlusCode
     */
    global_code: string;
}

/**
 * Check if a given object implements the PickupPlaceInformationPlusCode interface.
 */
export function instanceOfPickupPlaceInformationPlusCode(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "compound_code" in value;
    isInstance = isInstance && "global_code" in value;

    return isInstance;
}

export function PickupPlaceInformationPlusCodeFromJSON(json: any): PickupPlaceInformationPlusCode {
    return PickupPlaceInformationPlusCodeFromJSONTyped(json, false);
}

export function PickupPlaceInformationPlusCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PickupPlaceInformationPlusCode {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'compound_code': json['compound_code'],
        'global_code': json['global_code'],
    };
}

export function PickupPlaceInformationPlusCodeToJSON(value?: PickupPlaceInformationPlusCode | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'compound_code': value.compound_code,
        'global_code': value.global_code,
    };
}

