/* tslint:disable */
/* eslint-disable */
/**
 * Crypto Map API documentation
 * The Shop Directory API is serves a list of shops that accept crypto as a payment method.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PickupPlaceInformationAddressComponentsInner
 */
export interface PickupPlaceInformationAddressComponentsInner {
    /**
     * 
     * @type {string}
     * @memberof PickupPlaceInformationAddressComponentsInner
     */
    long_name: string;
    /**
     * 
     * @type {string}
     * @memberof PickupPlaceInformationAddressComponentsInner
     */
    short_name: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof PickupPlaceInformationAddressComponentsInner
     */
    types: Array<string>;
}

/**
 * Check if a given object implements the PickupPlaceInformationAddressComponentsInner interface.
 */
export function instanceOfPickupPlaceInformationAddressComponentsInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "long_name" in value;
    isInstance = isInstance && "short_name" in value;
    isInstance = isInstance && "types" in value;

    return isInstance;
}

export function PickupPlaceInformationAddressComponentsInnerFromJSON(json: any): PickupPlaceInformationAddressComponentsInner {
    return PickupPlaceInformationAddressComponentsInnerFromJSONTyped(json, false);
}

export function PickupPlaceInformationAddressComponentsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PickupPlaceInformationAddressComponentsInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'long_name': json['long_name'],
        'short_name': json['short_name'],
        'types': json['types'],
    };
}

export function PickupPlaceInformationAddressComponentsInnerToJSON(value?: PickupPlaceInformationAddressComponentsInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'long_name': value.long_name,
        'short_name': value.short_name,
        'types': value.types,
    };
}

